FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

WORKDIR /app
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip \
    libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender1 \
    procps \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

COPY requirements.txt .

RUN python -m pip install --upgrade pip setuptools wheel certifi
RUN python -m pip install --no-cache-dir --default-timeout=400 --retries 5 torch torchvision --index-url https://download.pytorch.org/whl/cu121
RUN python -m pip install --no-cache-dir --default-timeout=300 -r requirements.txt

COPY . .

CMD ["python", "-m", "app.worker"]